import {StyleSheet, type ViewStyle} from 'react-native';

const shadow: ViewStyle = {
  shadowColor: '#000000',
  shadowOffset: {width: 0, height: 12},
  shadowOpacity: 0.16,
  shadowRadius: 24,
  elevation: 8,
};

export const styles = StyleSheet.create({
  activeHeader: {
    alignItems: 'center',
    gap: 5,
    marginTop: 44,
  },
  addAppIcon: {
    alignItems: 'center',
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  addAppText: {
    fontSize: 24,
    fontWeight: '300',
    lineHeight: 26,
  },
  addTaskRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 50,
    paddingHorizontal: 13,
  },
  allowedBlock: {
    gap: 11,
    marginTop: 30,
  },
  allowedItem: {
    alignItems: 'center',
    flex: 1,
    gap: 6,
    minWidth: 54,
  },
  allowedLabel: {
    fontSize: 10,
    fontWeight: '600',
    maxWidth: 58,
  },
  allowedRow: {
    flexDirection: 'row',
    gap: 13,
  },
  appIcon: {
    alignItems: 'center',
    borderRadius: 11,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  appIconText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  appName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
  },
  appRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 13,
    minHeight: 48,
  },
  appSection: {
    gap: 6,
    marginTop: 18,
  },
  appSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 4,
  },
  backText: {
    fontSize: 30,
    fontWeight: '400',
    lineHeight: 32,
  },
  blockedWrap: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 44,
  },
  buttonPressed: {
    elevation: 1,
    opacity: 0.94,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    transform: [{translateY: 3}],
  },
  buttonRaised: {
    elevation: 5,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.18,
    shadowRadius: 0,
  },
  caption: {
    fontSize: 13,
    fontWeight: '600',
    marginTop: 28,
    textAlign: 'center',
  },
  checkCircle: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  checkMark: {
    fontSize: 12,
    fontWeight: '900',
  },
  darkAllowedAppsRow: {
    flexDirection: 'row',
    gap: 15,
    justifyContent: 'center',
  },
  darkAllowedPanel: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.055)',
    borderRadius: 20,
    gap: 14,
    marginHorizontal: 24,
    marginTop: 34,
    padding: 22,
  },
  darkAllowedTitle: {
    color: '#D8DEE6',
    fontSize: 12,
    fontWeight: '700',
  },
  darkBackButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    left: 14,
    position: 'absolute',
    top: 42,
    width: 44,
    zIndex: 2,
  },
  darkBackText: {
    color: '#F8FAFC',
    fontSize: 34,
    fontWeight: '400',
    lineHeight: 36,
  },
  darkChevron: {
    color: '#9CA3AF',
    fontSize: 22,
  },
  darkStatusBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 25,
    paddingTop: 16,
  },
  darkStatusText: {
    color: '#F7FAFC',
    fontSize: 13,
    fontWeight: '800',
  },
  darkSubtitle: {
    color: '#B8C0C8',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  darkSurface: {
    backgroundColor: '#0D1218',
    flex: 1,
    position: 'relative',
  },
  darkTaskCheck: {
    color: '#0D1218',
    fontSize: 11,
    fontWeight: '900',
  },
  darkTaskDot: {
    alignItems: 'center',
    borderColor: '#8A929C',
    borderRadius: 10,
    borderWidth: 1.5,
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  darkTaskDotComplete: {
    backgroundColor: '#55E07A',
    borderColor: '#55E07A',
  },
  darkTaskList: {
    gap: 9,
    marginHorizontal: 24,
    marginTop: 28,
  },
  darkTaskRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.11)',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 54,
    paddingHorizontal: 13,
  },
  darkTaskText: {
    color: '#F8FAFC',
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
  },
  darkTaskTextComplete: {
    color: '#98A2AE',
    textDecorationLine: 'line-through',
  },
  darkTitle: {
    color: '#F8FAFC',
    fontSize: 22,
    fontWeight: '800',
    textAlign: 'center',
  },
  divider: {
    height: StyleSheet.hairlineWidth,
  },
  doneBadge: {
    alignItems: 'center',
    backgroundColor: '#2B7D3E',
    borderRadius: 44,
    height: 88,
    justifyContent: 'center',
    width: 88,
    ...shadow,
  },
  doneCheck: {
    color: '#DDFCE5',
    fontSize: 42,
    fontWeight: '600',
  },
  doneWrap: {
    alignItems: 'center',
    flex: 1,
    gap: 20,
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  deleteTaskButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  deleteTaskText: {
    fontSize: 14,
    fontWeight: '800',
  },
  duration: {
    fontSize: 42,
    fontWeight: '300',
    letterSpacing: 0,
    marginTop: 7,
    textAlign: 'center',
  },
  durationInput: {
    alignSelf: 'center',
    fontSize: 42,
    fontWeight: '300',
    letterSpacing: 0,
    marginTop: 7,
    minWidth: 120,
    padding: 0,
    textAlign: 'center',
  },
  durationControls: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 14,
  },
  durationLabel: {
    fontSize: 17,
    fontWeight: '700',
    marginHorizontal: 35,
  },
  durationPart: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'center',
    width: 92,
  },
  durationPartInput: {
    fontSize: 42,
    fontWeight: '300',
    height: 54,
    letterSpacing: 0,
    margin: 0,
    padding: 0,
    textAlign: 'right',
    width: 56,
  },
  durationPartSuffix: {
    fontSize: 20,
    fontWeight: '800',
    marginLeft: 4,
  },
  durationPartText: {
    fontSize: 42,
    fontWeight: '300',
    letterSpacing: 0,
    textAlign: 'right',
    width: 56,
  },
  durationPartsRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'center',
    marginTop: 7,
  },
  emptyTaskDot: {
    borderRadius: 10,
    borderWidth: 1.3,
    height: 20,
    width: 20,
  },
  editorLabel: {
    fontSize: 13,
    fontWeight: '700',
  },
  endButton: {
    alignSelf: 'center',
    marginTop: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  endButtonText: {
    color: '#FF6B5F',
    fontSize: 14,
    fontWeight: '800',
  },
  endConfirmActions: {
    flexDirection: 'row',
    gap: 10,
  },
  endConfirmButton: {
    alignItems: 'center',
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 46,
  },
  endConfirmButtonText: {
    fontSize: 14,
    fontWeight: '900',
  },
  endConfirmEndButton: {
    flex: 3,
  },
  endConfirmStayButton: {
    flex: 7,
  },
  endConfirmCard: {
    borderWidth: 1,
    gap: 18,
    maxWidth: 320,
    paddingHorizontal: 18,
    paddingVertical: 20,
    width: '82%',
    ...shadow,
  },
  endConfirmOverlay: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 10,
  },
  endConfirmText: {
    fontSize: 17,
    fontWeight: '900',
    lineHeight: 24,
    textAlign: 'center',
  },
  hourglass: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.11)',
    borderRadius: 47,
    height: 94,
    justifyContent: 'center',
    marginBottom: 22,
    width: 94,
  },
  hourglassText: {
    color: '#F8FAFC',
    fontSize: 42,
  },
  lightDoneButton: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    justifyContent: 'center',
    margin: 24,
    minHeight: 56,
  },
  lightDoneButtonText: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
  },
  modeGrid: {
    flexDirection: 'row',
    gap: 13,
    justifyContent: 'center',
    marginTop: 28,
  },
  modeIcon: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1.5,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  modeIconText: {
    fontSize: 18,
    fontWeight: '800',
  },
  pixelModeIconBare: {
    borderRadius: 0,
    borderWidth: 0,
    height: 52,
    width: 52,
  },
  pixelModeIconText: {
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 34,
  },
  pixelTaskIconText: {
    fontSize: 22,
    lineHeight: 26,
  },
  pixelTimerIconText: {
    fontSize: 44,
    lineHeight: 46,
  },
  pixelIcon: {
    flexDirection: 'column',
  },
  pixelIconCell: {
    margin: 0,
  },
  pixelIconRow: {
    flexDirection: 'row',
  },
  pixelOctagonButton: {
    borderRadius: 0,
    borderWidth: 2,
    height: 48,
    width: 48,
  },
  pixelBurnFrame: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  pixelBurnSegment: {
    borderWidth: 1,
    height: 6,
    position: 'absolute',
    width: 6,
  },
  pixelBurnSpark: {
    height: 12,
    position: 'absolute',
    width: 12,
  },
  pixelBurnSparkBottom: {
    bottom: -3,
    left: 3,
  },
  pixelBurnSparkCell: {
    backgroundColor: '#000000',
    height: 6,
    position: 'absolute',
    width: 6,
  },
  pixelBurnSparkLeft: {
    left: -3,
    top: 3,
  },
  pixelBurnSparkRight: {
    right: -3,
    top: 3,
  },
  pixelBurnSparkTop: {
    left: 3,
    top: -3,
  },
  pixelLockFrame: {
    borderColor: '#000000',
    borderStyle: 'solid',
    borderWidth: 4,
    margin: 8,
  },
  pixelScreenFrame: {
    borderStyle: 'solid',
    borderWidth: 4,
    margin: 8,
    padding: 16,
  },
  modeLabel: {
    fontSize: 12,
    fontWeight: '800',
  },
  modeTile: {
    alignItems: 'center',
    borderWidth: 1,
    gap: 12,
    height: 128,
    justifyContent: 'center',
    width: 112,
    ...shadow,
  },
   pixelLine: {
    borderRadius: 0,
    borderStyle: 'solid',
    borderWidth: 2,
    elevation: 0,
    shadowOpacity: 0,
  },
   pixelDivider: {
    borderStyle: 'solid',
    borderTopWidth: 2,
    height: 0,
  },
   pixelText: {
    textTransform: 'uppercase',
  },
   pixelTaskDot: {
    borderRadius: 0,
    borderWidth: 2,
  },
   pixelTimerRing: {
    borderRadius: 0,
    borderWidth: 4,
  },
  inlineTaskInput: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    minHeight: 40,
    padding: 0,
  },
  page: {
    flexGrow: 1,
    paddingHorizontal: 21,
  },
  pauseButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderRadius: 27,
    height: 54,
    justifyContent: 'center',
    marginTop: 22,
    width: 54,
  },
  pauseText: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '900',
  },
  plus: {
    fontSize: 22,
    fontWeight: '300',
    width: 20,
  },
  previewBlocked: {
    alignItems: 'center',
    marginTop: 14,
    paddingVertical: 8,
  },
  previewBlockedText: {
    fontSize: 12,
    fontWeight: '700',
  },
  primaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 28,
    minHeight: 56,
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: '800',
  },
  progressDone: {
    color: '#55E07A',
    fontSize: 42,
    fontWeight: '300',
  },
  progressFill: {
    backgroundColor: '#55E07A',
    borderRadius: 3,
    height: 6,
  },
  progressTotal: {
    color: '#F8FAFC',
    fontSize: 42,
    fontWeight: '300',
  },
  progressTrack: {
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 3,
    height: 6,
    marginTop: 20,
    overflow: 'hidden',
    width: 260,
  },
  roundControl: {
    alignItems: 'center',
    borderRadius: 17,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  roundControlText: {
    fontSize: 22,
    fontWeight: '300',
    lineHeight: 24,
  },
  searchBox: {
    justifyContent: 'center',
    minHeight: 45,
    paddingHorizontal: 18,
  },
  searchText: {
    fontSize: 13,
    fontWeight: '600',
  },
  secondaryDarkButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    margin: 24,
    minHeight: 56,
  },
  secondaryDarkButtonText: {
    color: '#F8FAFC',
    fontSize: 15,
    fontWeight: '800',
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '700',
  },
  settingsButton: {
    alignItems: 'flex-end',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  settingsText: {
    fontSize: 20,
  },
  setupBackButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  setupTitle: {
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 31,
    marginTop: 26,
    textAlign: 'center',
  },
  setupTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 44,
  },
  statusSpacer: {
    height: 7,
  },
  taskActionText: {
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 22,
  },
  taskActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  taskCompleteBanner: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#193B25',
    borderColor: 'rgba(85,224,122,0.45)',
    borderRadius: 14,
    borderWidth: 1,
    elevation: 12,
    gap: 12,
    justifyContent: 'space-between',
    left: 32,
    minHeight: 120,
    paddingHorizontal: 16,
    paddingVertical: 18,
    position: 'absolute',
    right: 32,
    top: '50%',
    transform: [{translateY: -60}],
    zIndex: 5,
  },
  taskCompleteCountdown: {
    color: '#DDFCE5',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  taskCompleteBannerText: {
    color: '#DDFCE5',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  taskIconButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  taskProgressRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 26,
  },
  taskEditorBody: {
    gap: 12,
    marginTop: 28,
  },
  taskInput: {
    borderRadius: 9,
    borderWidth: 1,
    fontSize: 16,
    fontWeight: '700',
    minHeight: 54,
    paddingHorizontal: 14,
  },
  taskSetupList: {
    gap: 8,
    marginTop: 28,
  },
  taskSetupRow: {
    alignItems: 'center',
    borderRadius: 9,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 50,
    paddingHorizontal: 13,
  },
  taskSetupText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
  },
  taskSetupChevron: {
    fontSize: 20,
    fontWeight: '700',
  },
  themeCopy: {
    flex: 1,
    gap: 2,
  },
  themeList: {
    gap: 10,
    marginTop: 24,
  },
  themeName: {
    fontSize: 15,
    fontWeight: '900',
  },
  themePreview: {
    alignItems: 'center',
    borderColor: 'rgba(0,0,0,0.12)',
    borderRadius: 4,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 72,
  },
  themePreviewText: {
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
  },
  themeRow: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 13,
    minHeight: 68,
    paddingHorizontal: 13,
  },
  themeSample: {
    fontSize: 12,
    fontWeight: '700',
  },
  themeSelectedMark: {
    fontSize: 18,
    fontWeight: '900',
    width: 24,
  },
  timerRing: {
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: '#5E6670',
    borderRadius: 147,
    borderWidth: 4,
    height: 294,
    justifyContent: 'center',
    marginTop: 46,
    position: 'relative',
    width: 294,
  },
  timerText: {
    color: '#F8FAFC',
    fontSize: 55,
    fontWeight: '300',
    letterSpacing: 0,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 19,
    marginTop: 12,
  },
  topBarEnd: {
    width: 32,
  },
  topTitle: {
    fontSize: 16,
    fontWeight: '900',
  },
});
